application: mils-secure
version: optimized
runtime: python
api_version: 1

default_expiration: "30d"

handlers:
- url: /s
  static_dir: public
  secure: never
  
- url: /blank.html
  static_files: public/blank.html
  upload: public/blank.html
  secure: never
  
- url: /favicon.ico
  static_files: public/image/icon/favicon.png
  upload: public/image/icon/favicon.png
  secure: never

- url: /robots.txt
  static_files: public/robots.txt
  upload: public/robots.txt
  expiration: 7d
  secure: never
 
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/deferred.py
  login: admin

- url: /console/static/
  static_dir: console/app/view/static
  expiration: 7d

- url: /console.*
  script: console/app/console.py
  login: admin
 
- url: /dl.*
  script: static.py

- url: /admin.*
  script: admin.py
  login: admin
  
- url: /worker.*
  script: workers.py
  login: admin
  
- url: /api.*
  script: api.py
  login: admin
  
- url: /rpc.*
  script: rpc.py
  login: admin
  
- url: /account.*
  script: accounts.py
  
- url: /.*
  script: handlers.py
